"""Add total_cost  column to Booking

Revision ID: ccc099bc4458
Revises: f28f31d98552
Create Date: 2025-02-03 15:20:12.594180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ccc099bc4458'
down_revision: Union[str, None] = 'f28f31d98552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('total_cost', sa.DECIMAL(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'total_cost')
    op.create_table('car',
    sa.Column('car_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('make', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('mileage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('availability', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('minimum_rent_period', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('maximum_rent_period', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('rate_per_day', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('building_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address_line_1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address_line_2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('town', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('customer_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('price_list_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'customer', ['id'], unique=True)
    op.create_index('email', 'customer', ['email'], unique=True)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('dob', mysql.DATETIME(), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='user_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'user', ['id'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
